# Sound effects for the toys. WAVs in assets/sfx are generated by assets/sfx/make_sfx.py.
# The folder has .gdignore, so files load raw at runtime and need no editor import.
extends Node
const DIR: String = "res://assets/sfx/"
const VOICES: int = 12
# Per-sound loudness (dB) and random pitch spread so repeats don't sound identical.
const MIX: Dictionary = {
	"golem_step": [-7.0, 0.08], "golem_slam": [-1.0, 0.04], "golem_stomp": [-1.0, 0.04], "golem_windup": [-6.0, 0.05],
	"golem_sweep": [-3.0, 0.05], "golem_kneel": [-2.0, 0.0], "golem_land": [-1.0, 0.0], "golem_die": [0.0, 0.0],
	"golem_shake": [-4.0, 0.05], "rock_pop": [-8.0, 0.15], "rock_hit": [-2.0, 0.08], "weak_hit": [-2.0, 0.05],
	"body_hit": [-4.0, 0.1], "swing": [-9.0, 0.12], "jump": [-5.0, 0.1], "wall_jump": [-4.0, 0.1], "dash": [-7.0, 0.08],
	"dodge": [-6.0, 0.05], "grab": [-5.0, 0.05], "launch": [-4.0, 0.05], "hurt": [-2.0, 0.04], "death": [-3.0, 0.0],
	"checkpoint": [-5.0, 0.0], "goal": [-4.0, 0.0], "win": [-3.0, 0.0],
}
var streams: Dictionary = {}
var voices: Array[AudioStreamPlayer] = []
var next_voice: int = 0
var muted: bool = false
# Every play() call in order, for tests.
var played: Array[String] = []

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for sound: String in MIX:
		var stream: AudioStreamWAV = AudioStreamWAV.load_from_file(DIR+sound+".wav")
		if stream == null:
			push_warning("Missing sound: "+sound)
			continue
		streams[sound] = stream
	for i: int in VOICES:
		var voice: AudioStreamPlayer = AudioStreamPlayer.new()
		add_child(voice)
		voices.append(voice)

func play(sound: String, volume_db: float = 0.0) -> void:
	if not MIX.has(sound):
		push_error("Unknown sound: "+sound)
		return
	played.append(sound)
	if muted or not streams.has(sound): return
	# Round-robin voices; the oldest sound gets cut when all are busy.
	var voice: AudioStreamPlayer = voices[next_voice]
	next_voice = (next_voice+1) % voices.size()
	voice.stream = streams[sound]
	voice.volume_db = float(MIX[sound][0])+volume_db
	voice.pitch_scale = 1.0+randf_range(-1,1)*float(MIX[sound][1])
	voice.play()
