extends "res://tests/PlayerSuite.gd"

func tap(code: Key) -> void:
	key(code,true)
	key(code,false)

func wait_strike() -> void:
	for tick: int in 120:
		if player.attack_spawned: return
		await frames(1)
	check(false,"strike spawned within bounded wait")

func _run() -> void:
	Tuning.set_value("dummy","enabled",false)
	Tuning.feedback["hitstop_on_hit"] = 0
	arena = load("res://scenes/arena/Arena.tscn").instantiate()
	add_child(arena)
	player = arena.player
	dummy = arena.dummy
	await frames(10)
	# Every weapon and every stage, including the slow fourth-to-first transition.
	for id: String in ["sword_basic","greatsword_slab","daggers_twin"]:
		Tuning.set_value("practice","weapon_id",id)
		for stage: int in 4:
			await reset_player()
			player.combo_index = posmod(stage-1,4)
			player.combo_remaining = 1
			tap(KEY_J)
			await frames(1)
			await wait_strike()
			tap(KEY_J)
			await frames(1)
			var next: int = (stage+1)%4
			for tick: int in 100:
				if player.combo_index == next: break
				await frames(1)
			check(player.combo_index == next,id+" active tap chains stage "+str(stage+1))
			await frames(130)
			check(not player.attack_running and player.combo_index == next,id+" queued tap runs exactly once")
	Tuning.set_value("practice","weapon_id","sword_basic")
	await reset_player()
	key(KEY_D,true)
	key(KEY_W,true)
	tap(KEY_J)
	key(KEY_W,false)
	await frames(1)
	await wait_strike()
	check(player.attack_kind == "up_attack" and player.active_box.position.y < 0,"D held plus brief W+J preserves up hitbox")
	await reset_player(800,400)
	key(KEY_D,true)
	tap(KEY_SHIFT)
	await frames(1)
	key(KEY_S,true)
	tap(KEY_J)
	key(KEY_S,false)
	await frames(1)
	await wait_strike()
	check(player.attack_kind == "down_attack" and player.active_box.position.y > 0,"D dash plus brief S+J preserves down hitbox")
	await reset_player(800,400)
	tap(KEY_SHIFT)
	key(KEY_W,true)
	await frames(1)
	check(player.dash_direction == Vector2.UP,"Shift before W in one tick resolves current direction")
	await reset_player(800,400)
	tap(KEY_SHIFT)
	await frames(1)
	key(KEY_W,true)
	await frames(1)
	check(player.dash_direction == Vector2.UP,"neutral dash accepts next-tick direction")
	key(KEY_W,false)
	key(KEY_S,true)
	await frames(1)
	check(player.dash_direction == Vector2.UP,"reaim locks after first explicit direction")
	await reset_player(800,400)
	tap(KEY_SHIFT)
	await frames(5)
	key(KEY_W,true)
	await frames(1)
	check(player.dash_direction == Vector2.RIGHT,"late direction cannot steer locked dash")
	Tuning.set_value("practice","weapon_id","greatsword_slab")
	await reset_player(800,912)
	tap(KEY_J)
	await frames(3)
	key(KEY_A,true)
	tap(KEY_SHIFT)
	await frames(1)
	check(not player.attack_running and player.state == GatePlayer.State.DASH,"escape cancels slow attack startup")
	await frames(14)
	check(not player.attack_running and is_equal_approx(player.velocity.x,-player.p("move_speed")),"escape ends in full-speed locomotion without recovery")
	Tuning.set_value("practice","weapon_id","sword_basic")
	await reset_player(800,830)
	player.velocity.y = 900
	player.coyote = 0
	tap(KEY_SPACE)
	var jumped: bool = false
	var peak: float = 912
	for tick: int in 45:
		await frames(1)
		if player.velocity.y < 0: jumped = true
		if jumped: peak = minf(peak,player.position.y)
	check(jumped and 912-peak < 100,"released landing-buffer jump is a short hop")
	await reset_player()
	key(KEY_SPACE,true)
	tap(KEY_SHIFT)
	await frames(3)
	check(player.velocity.y < 0 and player.position.y < 912,"same-tick jump+dash consumes jump buffer")
	await reset_player()
	tap(KEY_J)
	await frames(10)
	key(KEY_W,true)
	tap(KEY_J)
	key(KEY_W,false)
	await frames(12)
	check(player.attack_kind == "up_attack" and player.combo_display_time == 0,"special attack clears combo display")
	tap(KEY_J)
	await frames(35)
	check(player.attack_kind == "combo" and player.combo_index == 0,"normal attack after special starts at first hit")
	await reset_player()
	key(KEY_K,true)
	tap(KEY_J)
	key(KEY_K,false)
	await frames(1)
	check(player.parry_attack_pending and not player.attack_running,"parry+attack waits for success")
	var box: CombatHitbox = CombatHitbox.new()
	box.parriable = true
	box.damage = 1
	player.receive_hit(box)
	box.free()
	check(player.attack_running and not player.parry_attack_pending,"successful parry consumes one immediate counter")
	Feedback.clear_transients()
	await frames(90)
	check(not player.attack_running,"successful counter does not repeat after tap")
	await reset_player()
	key(KEY_K,true)
	key(KEY_J,true)
	key(KEY_K,false)
	await frames(50)
	check(not player.parry_attack_pending and not player.attack_running and player.attack_queued_until == 0,"failed parry drops simultaneous held attack")
	await reset_player()
	key(KEY_J,true)
	await frames(1)
	player.controls._notification(NOTIFICATION_APPLICATION_FOCUS_OUT)
	player.clear_action_intent()
	player.controls._notification(NOTIFICATION_APPLICATION_FOCUS_IN)
	await frames(1)
	check(not player.controls.just_pressed(&"attack") and not player.attack_running,"focus resume seeds held key without new edge")
	await reset_player()
	# Dash-origin attacks obey their own continuation option.
	for keep: bool in [true,false]:
		Tuning.set_value("player","dash_attack_continues_after_dash",keep)
		await reset_player(800,400)
		key(KEY_D,true)
		tap(KEY_SHIFT)
		await frames(6)
		tap(KEY_J)
		await frames(7)
		check(player.attack_running == keep,"dash-origin attack continuation option "+str(keep))
	Tuning.set_value("player","dash_attack_continues_after_dash",true)
	await reset_player()
	key(KEY_J,true)
	await frames(1)
	player.clear_action_intent()
	player.controls.device_id = 0
	player.controls.clear_history()
	player.controls._seed_held()
	tap(KEY_D)
	await frames(1)
	check(not player.controls.just_pressed(&"attack") and not player.attack_running,"device switch does not synthesize held attack")
	await reset_player()
	# Legacy saved options retain user values while removed UI fields are retired.
	var legacy: Dictionary = Tuning.defaults.duplicate(true)
	legacy["player"]["dash_keeps_attack"] = false
	legacy["player"].erase("dash_attack_continues_after_dash")
	legacy["player"].erase("dash_direction_grace")
	legacy["player"]["input_edge_lifetime"] = 0.18
	var old_path: String = Tuning.storage_override
	Tuning.storage_override = old_path+".legacy"
	var legacy_file: FileAccess = FileAccess.open(Tuning.storage_override,FileAccess.WRITE)
	legacy_file.store_string(JSON.stringify(legacy))
	legacy_file.close()
	check(Tuning.load_override() and not Tuning.player["dash_attack_continues_after_dash"] and Tuning.player["dash_direction_grace"] == 0.05,"legacy tuning migrates option and fills grace")
	check(not Tuning.player.has("input_edge_lifetime"),"obsolete edge lifetime is removed")
	Tuning.storage_override = old_path
	Tuning.reset_defaults()
	Tuning.set_value("dummy","enabled",false)
	# A valid modern save is a no-op across repeated loads; interrupted replacement recovers.
	check(GameState.commit(GameState.fresh()),"fresh isolated save written")
	var original: String = FileAccess.get_file_as_string(GameState.storage_path)
	for i: int in 3: check(GameState.load_save() and not GameState.migration_changed,"modern save load has no migration "+str(i))
	check(not FileAccess.file_exists(GameState.storage_path+".pre-migrate.bak"),"modern loads create no migration backup")
	var next: Dictionary = GameState.state.duplicate(true)
	next["materials"]["golem_shard"] = 9
	check(GameState.commit(next),"distinct save rotates backup")
	GameState.save()
	check(FileAccess.get_file_as_string(GameState.storage_path+".bak") == original,"unchanged hub save preserves previous state backup")
	DirAccess.copy_absolute(GameState.storage_path,GameState.storage_path+".tmp")
	DirAccess.remove_absolute(GameState.storage_path)
	check(GameState.load_save() and GameState.state["materials"]["golem_shard"] == 9,"missing main recovers valid tmp before bak")
	DirAccess.remove_absolute(GameState.storage_path)
	DirAccess.remove_absolute(GameState.storage_path+".tmp")
	check(GameState.load_save() and GameState.state["materials"]["golem_shard"] == 0,"missing main recovers backup")
	var file: FileAccess = FileAccess.open(GameState.storage_path+".bak",FileAccess.WRITE)
	file.store_string("invalid")
	file.close()
	DirAccess.remove_absolute(GameState.storage_path)
	check(not GameState.load_save() and GameState.save_blocked,"invalid recovery blocks new-save overwrite")
	GameState.save_blocked = false
	# Result input: protect keyboard, pad, pointer and arena retry route.
	arena.queue_free()
	await frames(3)
	Tuning.player = DataRegistry.documents["tuning/player.json"].duplicate(true)
	Tuning.weapons = DataRegistry.documents["weapons.json"].duplicate(true)
	check(not Tuning.combat_modified(),"canonical combat settings are unmodified")
	Tuning.set_value("player","dash_iframe",0.7)
	arena = load("res://scenes/arena/BattleArena.tscn").instantiate()
	add_child(arena)
	player = arena.player
	check(arena.debug_used,"pre-battle tuning marks run debug-used")
	arena.boss.position.y -= 200
	arena.boss.enabled = true
	arena.boss.stagger_time = 1
	var before_y: float = arena.boss.position.y
	await frames(3)
	check(arena.boss.position.y > before_y,"staggered airborne golem keeps falling")
	arena.finish(false)
	await snapshot("independent_result_locked")
	var result: PanelContainer = arena.result_screen
	var counter: Array[int] = [0]
	result.retry_requested.disconnect(arena.restart)
	result.retry_requested.connect(func() -> void: counter[0] += 1)
	tap(KEY_SPACE)
	tap(KEY_R)
	pad(JOY_BUTTON_A,true)
	await frames(45)
	check(counter[0] == 0 and not result.input_ready,"result ignores immediate keys and waits for held pad release")
	pad(JOY_BUTTON_A,false)
	await frames(3)
	check(result.input_ready,"result arms after delay and all gameplay keys released")
	await snapshot("independent_result_ready")
	tap(KEY_SPACE)
	await frames(2)
	check(counter[0] == 1,"fresh accept after arming activates retry once")
	arena.queue_free()
	await frames(3)
	print("INDEPENDENT_REVIEW_RESULT checks=%d failures=%d" % [checks,failures])
	get_tree().quit(0 if failures == 0 else 1)
