extends "res://tests/ControlsRevisionSuite.gd"

func _run() -> void:
	arena = load("res://scenes/arena/Arena.tscn").instantiate()
	add_child(arena)
	player = arena.player
	dummy = arena.dummy
	Tuning.set_value("dummy","enabled",false)
	await frames(10)
	await reset_player()
	key(KEY_J,true)
	await frames(7)
	key(KEY_J,false)
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(12)
	check(player.attack_running and player.combo_index == 1,"early short second tap chains into strike 2")
	await reset_player()
	key(KEY_K,true)
	await frames(10)
	key(KEY_K,false)
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(1)
	check(not player.attack_running and player.state == GatePlayer.State.PARRY,"attack tap cannot cancel failed parry recovery")
	await reset_player()
	key(KEY_SHIFT,true)
	await frames(1)
	key(KEY_SPACE,true)
	key(KEY_SPACE,false)
	await frames(14)
	check(player.position.y < 900,"jump tap during ground dash is honored")
	await reset_player()
	key(KEY_W,true)
	key(KEY_SHIFT,true)
	key(KEY_SHIFT,false)
	key(KEY_W,false)
	await frames(1)
	check(player.state == GatePlayer.State.DASH and player.dash_direction == Vector2.UP,"between-tick W+Shift tap preserves upward dash direction")
	await reset_player()
	key(KEY_W,true)
	key(KEY_J,true)
	key(KEY_J,false)
	key(KEY_W,false)
	await frames(1)
	check(player.attack_kind == "up_attack","between-tick W+J tap preserves attack direction")
	# Tap survives release only until one next strike; never repeats without intent.
	await reset_player()
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(2)
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(40)
	check(not player.attack_running and player.combo_index == 1,"early second tap executes exactly one next strike")
	await reset_player()
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(2)
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(1)
	OS.delay_msec(210)
	await frames(30)
	check(player.combo_index == 1,"early tap survives current attack across wall-clock stall")
	await reset_player()
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(2)
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(1)
	player.controls._notification(NOTIFICATION_APPLICATION_FOCUS_OUT)
	player.controls._notification(NOTIFICATION_APPLICATION_FOCUS_IN)
	await frames(30)
	check(player.combo_index == 0,"focus change invalidates attack queue")
	await reset_player()
	key(KEY_K,true)
	key(KEY_K,false)
	await frames(2)
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(1)
	check(player.state == GatePlayer.State.PARRY,"attack cannot erase live parry window")
	await frames(6)
	check(not player.attack_running and player.state == GatePlayer.State.PARRY,"tap during live parry does not bypass failed recovery")
	await reset_player()
	key(KEY_K,true)
	await frames(10)
	key(KEY_SPACE,true)
	await frames(1)
	check(player.velocity.y >= 0 and player.state == GatePlayer.State.PARRY,"jump cannot cancel failed parry recovery")
	await reset_player()
	key(KEY_K,true)
	key(KEY_D,true)
	await frames(1)
	check(player.velocity.x > 0,"parry does not freeze directional movement")
	await reset_player()
	key(KEY_SHIFT,true)
	key(KEY_J,true)
	await frames(1)
	check(player.state == GatePlayer.State.DASH and player.attack_running,"same-tick dash and attack both execute")
	await reset_player()
	key(KEY_SHIFT,true)
	await frames(1)
	var shifted: InputEventKey = InputEventKey.new()
	shifted.physical_keycode = KEY_J
	shifted.keycode = KEY_J
	shifted.shift_pressed = true
	shifted.pressed = true
	Input.parse_input_event(shifted)
	Input.flush_buffered_events()
	shifted = shifted.duplicate()
	shifted.pressed = false
	Input.parse_input_event(shifted)
	Input.flush_buffered_events()
	await frames(1)
	check(player.attack_running,"Shift modifier plus between-tick J tap is received")
	await reset_player()
	pad(JOY_BUTTON_X,true)
	await frames(2)
	pad(JOY_BUTTON_X,false)
	pad(JOY_BUTTON_X,true)
	pad(JOY_BUTTON_X,false)
	await frames(20)
	check(player.combo_index == 1,"pad early tap chains once like keyboard")
	await reset_player()
	key(KEY_J,true)
	await frames(2)
	key(KEY_K,true)
	key(KEY_SHIFT,true)
	await frames(1)
	check(player.state == GatePlayer.State.DASH and player.parry_age <= player.p("parry_window") and not player.attack_running,"parry and dash override attack queue together")
	for weapon: Dictionary in Tuning.weapons:
		Tuning.set_value("practice","weapon_id",weapon["id"])
		await reset_player(800,912)
		check(player.weapon["combo"].size() == 4,weapon["id"]+" has four strikes")
		var seen: Array[int] = []
		key(KEY_J,true)
		for i: int in 200:
			await frames(1)
			if player.attack_spawned and not player.combo_index in seen:
				seen.append(player.combo_index)
				check(player.combo_display_index == player.combo_index,"visual stage matches live hitbox "+weapon["id"]+str(player.combo_index))
				await snapshot("combo_"+weapon["id"]+"_"+str(player.combo_index+1))
			if seen.size() == 4: break
		check(seen == [0,1,2,3],weapon["id"]+" held attack advances in order 1-2-3-4")
		key(KEY_J,false)
		await frames(50)
		key(KEY_J,true)
		await frames(1)
		check(player.combo_index == 0,"combo timeout returns to strike 1")
	Tuning.set_value("practice","weapon_id","sword_basic")
	await reset_player()
	key(KEY_J,true)
	key(KEY_J,false)
	await frames(2)
	key(KEY_W,true)
	key(KEY_J,true)
	key(KEY_J,false)
	key(KEY_W,false)
	await frames(18)
	check(player.attack_kind == "up_attack","early directional tap survives until chain permission")
	await reset_player()
	key(KEY_W,true)
	key(KEY_SHIFT,true)
	key(KEY_W,false)
	key(KEY_SHIFT,false)
	key(KEY_J,true)
	key(KEY_K,true)
	await frames(1)
	check(player.state == GatePlayer.State.DASH and player.dash_direction == Vector2.UP and player.parry_age <= player.p("parry_window"),"four-key sequence preserves separate dash direction and parry priority")
	var original: Array = Tuning.weapons.duplicate(true)
	var legacy: Dictionary = {"player":Tuning.player,"feedback":Tuning.feedback,"weapons":original.duplicate(true),"training":Tuning.training}
	legacy["weapons"][0]["combo"].resize(3)
	legacy["weapons"][1]["combo"].resize(2)
	legacy["weapons"][0]["combo"][0]["damage"] = 13
	var path: String = Tuning.storage_override
	Tuning.storage_override = path+".legacy"
	var file: FileAccess = FileAccess.open(Tuning.storage_override,FileAccess.WRITE)
	file.store_string(JSON.stringify(legacy))
	file.close()
	check(Tuning.load_override() and Tuning.get_weapon("sword_basic")["combo"].size() == 4 and Tuning.get_weapon("greatsword_slab")["combo"].size() == 4,"legacy saved weapon arrays migrate to four strikes")
	check(Tuning.get_weapon("sword_basic")["combo"][0]["damage"] == 13,"legacy migration preserves edited existing strikes")
	Tuning.weapons = original
	Tuning.storage_override = path
	Tuning.changed.emit()
	# Exercise real mouse navigation while this test node remains outside current_scene.
	await reset_player()
	arena.queue_free()
	await frames(2)
	var hub: Control = load("res://scenes/hub/Hub.tscn").instantiate()
	get_tree().root.add_child(hub)
	get_tree().current_scene = hub
	await frames(4)
	await snapshot("combo_hub_modes")
	check(hub.practice_button.text.contains("연습 모드") and hub.boss_buttons["golem"].text.contains("실제 게임"),"hub labels both modes explicitly")
	await click_button(hub.practice_button)
	await frames(4)
	arena = get_tree().current_scene
	check(arena.scene_file_path.ends_with("/Arena.tscn") and not GameState.progression_run,"practice button enters reward-free training")
	await click_button(find_back(arena.debug_panel.toolbar))
	await frames(4)
	hub = get_tree().current_scene
	check(hub.scene_file_path.ends_with("Hub.tscn"),"practice toolbar returns to hub")
	await click_button(hub.boss_buttons["golem"])
	await frames(45)
	arena = get_tree().current_scene
	check(arena.scene_file_path.ends_with("BattleArena.tscn") and GameState.progression_run and arena.player.use_loadout,"actual game button uses equipped progression")
	await snapshot("combo_game_mode")
	arena.debug_panel.toggle()
	await frames(2)
	await click_button(find_back(arena.debug_panel.practice_buttons["닫고 연습"].get_parent()))
	await frames(4)
	hub = get_tree().current_scene
	check(hub.scene_file_path.ends_with("Hub.tscn") and not get_tree().paused,"paused real-game return unpauses hub")
	await click_button(hub.practice_button)
	await frames(4)
	arena = get_tree().current_scene
	var preview: Button
	for child: Node in arena.debug_panel.toolbar.get_children():
		if child is Button and child.text.contains("골렘 연습"): preview = child
	await click_button(preview)
	await frames(45)
	arena = get_tree().current_scene
	check(not GameState.progression_run and not arena.player.use_loadout,"practice boss preserves no-reward mode")
	var before: Dictionary = GameState.state.duplicate(true)
	arena.finish(true)
	await frames(2)
	check(GameState.state == before,"practice victory grants no resources or records")
	while not arena.result_screen.input_ready: await frames(1)
	await click_button(arena.result_screen.return_button)
	await frames(4)
	check(get_tree().current_scene.scene_file_path.ends_with("Hub.tscn"),"practice result returns to hub")
	print("INPUT_COMBO_RESULT checks=%d failures=%d" % [checks,failures])
	get_tree().quit(0 if failures == 0 else 1)

func find_back(parent: Node) -> Button:
	for child: Node in parent.get_children():
		if child is Button and child.text == "허브로 돌아가기": return child
	return null
