extends "res://tests/PlayerSuite.gd"

func tap_bow() -> void:
	# Native runs can lose desktop focus while the user works in another app.
	# This helper explicitly delivers a synthetic foreground press. Focus loss itself is tested separately.
	if not player.controls._focused:
		print("GPU_TEST restoring synthetic input focus")
		player.controls._notification(NOTIFICATION_APPLICATION_FOCUS_IN)
	key(KEY_U,true)
	key(KEY_U,false)
	await frames(1)

func _run() -> void:
	Tuning.set_value("dummy","enabled",false)
	Tuning.feedback["hitstop_on_hit"] = 0
	arena = load("res://scenes/arena/Arena.tscn").instantiate()
	add_child(arena)
	player = arena.player
	dummy = arena.dummy
	await frames(10)
	check(InputMap.has_action("magic_bow"),"bow action registered")
	check(arena.debug_panel.controls.has("player/bow_turn_rate") and arena.debug_panel.controls.has("player/bow_charge_time"),"bow has editable tuning controls")
	await reset_player(800,912)
	player.facing = -1
	await tap_bow()
	var arrow: MagicArrow = player.bow.last_arrow
	check(is_instance_valid(arrow) and arrow.target.combatant == dummy and arrow.motion.x > 0,"tap auto-aims behind facing toward enemy")
	check(arrow.damage == player.p("bow_damage_min"),"tap damage uses configured minimum")
	var before: float = dummy.damage_received
	await frames(55)
	check(dummy.damage_received == before+player.p("bow_damage_min"),"fast arrow lands exactly one hit")
	await reset_player(800,912)
	key(KEY_U,true)
	key(KEY_A,true)
	await frames(6)
	check(player.bow.charging and player.velocity.x == -player.p("move_speed"),"charging keeps full movement speed")
	key(KEY_SHIFT,true)
	await frames(1)
	key(KEY_SHIFT,false)
	check(player.state == GatePlayer.State.DASH and player.bow.charging,"dash preserves bow charge")
	var count: int = player.bow.shots_fired
	key(KEY_U,false)
	await frames(1)
	arrow = player.bow.last_arrow
	check(player.state == GatePlayer.State.DASH and player.bow.shots_fired == count+1,"release fires during dash without cancelling movement")
	check(arrow.global_position.distance_to(player.global_position) < 1,"arrow spawns at post-movement player position")
	await reset_player(800,912)
	key(KEY_U,true)
	await frames(60)
	check(player.bow.ratio() == 1 and player.bow.charging,"full charge waits for release")
	await snapshot("bow_full_charge")
	player.position.x = 1000 # Models a future blink without resetting the ability.
	key(KEY_U,false)
	await frames(1)
	arrow = player.bow.last_arrow
	check(arrow.damage == player.p("bow_damage_max") and arrow.speed == player.p("bow_speed_max"),"full charge increases damage and speed")
	check(absf(arrow.position.x-1000) < 1,"future teleport relocation preserves charge and updates origin")
	before = dummy.damage_received
	await frames(30)
	check(dummy.damage_received == before+player.p("bow_damage_max"),"charged arrow hits only once")
	await reset_player(800,400)
	key(KEY_U,true)
	key(KEY_D,true)
	key(KEY_SHIFT,true)
	await frames(2)
	key(KEY_SHIFT,false)
	check(player.bow.charging and player.state == GatePlayer.State.DASH,"air dash and charge coexist")
	key(KEY_U,false)
	await frames(1)
	await snapshot("bow_air_dash_release")
	check(player.state == GatePlayer.State.DASH and player.bow.last_arrow.motion.y > 0,"airborne arrow aims down at enemy automatically")
	await reset_player(800,912)
	await tap_bow()
	count = player.bow.shots_fired
	await tap_bow()
	check(player.bow.shots_fired == count,"cooldown rejects repeated tap")
	key(KEY_U,true)
	await frames(100)
	check(player.bow.shots_fired == count and not player.bow.charging,"cooldown press does not become a delayed shot")
	key(KEY_U,false)
	await frames(1)
	await tap_bow()
	print("BOW_REPRESS shots=",player.bow.shots_fired," expected=",count+1," cooldown=",player.bow.cooldown," focused=",player.controls._focused," received=",player.controls.received.get(&"magic_bow",0))
	check(player.bow.shots_fired == count+1,"fresh press after cooldown works")
	await reset_player(800,912)
	key(KEY_U,true)
	await frames(4)
	player.controls.set_blocked(true)
	player.clear_action_intent()
	key(KEY_U,false)
	count = player.bow.shots_fired
	player.controls.set_blocked(false)
	await frames(2)
	check(not player.bow.charging and player.bow.shots_fired == count,"menu boundary cancels charge without release shot")
	key(KEY_U,true)
	await frames(4)
	player.controls._notification(NOTIFICATION_APPLICATION_FOCUS_OUT)
	await frames(1)
	player.controls._notification(NOTIFICATION_APPLICATION_FOCUS_IN)
	key(KEY_U,false)
	await frames(1)
	check(not player.bow.charging and player.bow.shots_fired == count,"focus boundary cancels charge without ghost shot")
	await reset_player()
	key(KEY_U,true)
	await frames(4)
	var hit: CombatHitbox = CombatHitbox.new()
	hit.damage = 1
	player.receive_hit(hit)
	hit.free()
	key(KEY_U,false)
	await frames(1)
	check(not player.bow.charging and player.bow.shots_fired == count,"hurt cancels charge without firing")
	Feedback.clear_transients()
	await reset_player()
	pad(JOY_BUTTON_RIGHT_SHOULDER,true)
	await frames(4)
	check(player.bow.charging and player.controls.device_id == 0,"RB charges on gamepad")
	pad(JOY_BUTTON_B,true)
	await frames(1)
	pad(JOY_BUTTON_B,false)
	pad(JOY_BUTTON_RIGHT_SHOULDER,false)
	await frames(1)
	check(player.bow.shots_fired == count+1 and player.state == GatePlayer.State.DASH,"RB release during pad dash fires")
	await reset_player(800,912)
	await tap_bow()
	arrow = player.bow.last_arrow
	var old_angle: float = arrow.motion.angle()
	dummy.position.y -= 250
	await frames(1)
	check(arrow.motion.angle() < old_angle,"guidance follows moving target")
	check(absf(arrow.motion.angle()-old_angle) <= player.p("bow_turn_rate")/60+0.001,"guidance respects turn-rate limit")
	dummy.position.y += 250
	await reset_player()
	dummy.hide()
	player.facing = -1
	await tap_bow()
	arrow = player.bow.last_arrow
	check(arrow.target == null and arrow.motion == Vector2.LEFT,"no target falls back to facing direction")
	await frames(130)
	check(not is_instance_valid(arrow),"missed arrow expires instead of orbiting forever")
	dummy.show()
	check(MagicArrow.sweep_fraction(Vector2.ZERO,Vector2(1000,0),Rect2(500,-5,1,10)) >= 0,"sweep detects thin target crossed in one tick")
	check(MagicArrow.sweep_fraction(Vector2.ZERO,Vector2(1000,0),Rect2(500,10,1,10)) < 0,"sweep rejects near miss")
	for weapon: String in ["sword_basic","greatsword_slab","daggers_twin"]:
		Tuning.set_value("practice","weapon_id",weapon)
		await reset_player()
		await tap_bow()
		check(player.bow.last_arrow.damage == player.p("bow_damage_min"),weapon+" supports the same auxiliary bow")
	# Preview the new tab and verify persisted values, including older overrides.
	arena.debug_panel.tabs.current_tab = 3
	arena.debug_panel.toggle()
	await snapshot("bow_tuning")
	arena.debug_panel.toggle()
	Tuning.set_value("player","bow_damage_max",60)
	check(Tuning.save_values(),"bow tuning saves to isolated override")
	Tuning.set_value("player","bow_damage_max",48)
	check(Tuning.load_override() and player.p("bow_damage_max") == 60,"bow tuning restores")
	var legacy: Dictionary = Tuning.defaults.duplicate(true)
	for field: String in legacy["player"].keys():
		if field.begins_with("bow_"): legacy["player"].erase(field)
	var file: FileAccess = FileAccess.open(Tuning.storage_override,FileAccess.WRITE)
	file.store_string(JSON.stringify(legacy))
	file.close()
	check(Tuning.load_override() and Tuning.player["bow_damage_max"] == 48,"pre-bow override receives bow defaults")
	arena.queue_free()
	await frames(3)
	GameState.progression_run = true
	arena = load("res://scenes/arena/BattleArena.tscn").instantiate()
	add_child(arena)
	player = arena.player
	await frames(55)
	arena.boss.set_physics_process(false)
	arena.boss.interrupt()
	await reset_player(800,912)
	key(KEY_U,true)
	await frames(50)
	check(player.bow.target == arena.boss.hurtbox,"progression loadout auto-locks boss")
	await snapshot("bow_boss_charge")
	before = arena.boss.hp
	key(KEY_U,false)
	await frames(35)
	check(arena.boss.hp < before,"bow damages actual boss in progression battle")
	await reset_player()
	arena.boss.vulnerable = false
	await tap_bow()
	check(is_instance_valid(player.bow.last_arrow) and player.bow.last_arrow.target == null,"invulnerable boss is not marked as target")
	arena.boss.vulnerable = true
	await reset_player()
	key(KEY_U,true)
	await frames(2)
	arena.boss.hp = 0
	await frames(1)
	check(player.bow.target == null,"dead target is released safely")
	count = player.bow.shots_fired
	arena.finish(false)
	key(KEY_U,false)
	await frames(2)
	check(not player.bow.charging and player.bow.shots_fired == count,"result transition cancels bow without firing")
	arena.queue_free()
	await frames(3)
	print("MAGIC_BOW_RESULT checks=%d failures=%d" % [checks,failures])
	get_tree().quit(0 if failures == 0 else 1)
