"""Standard-library-only fixture builder. Pass a scratch destination outside data/."""
from pathlib import Path
import copy, json, sys

project=Path(__file__).resolve().parents[1]
destination=Path(sys.argv[1]).resolve()
original={p.relative_to(project/'data').as_posix():json.loads(p.read_text(encoding='utf-8')) for p in (project/'data').rglob('*.json')}
manifest=[]
canonical_golem=copy.deepcopy(original["bosses/golem.json"])
original["bosses/golem.json"]=json.loads((project/"tests/fixtures/legacy_golem.json").read_text())
def case(name,mutate,errors=(),valid=False):
    data=copy.deepcopy(original)
    mutate(data)
    root=destination/name
    root.mkdir(parents=True,exist_ok=True)
    for path,value in data.items():
        p=root/path;p.parent.mkdir(parents=True,exist_ok=True)
        p.write_text(value if isinstance(value,str) else json.dumps(value,ensure_ascii=False),encoding='utf-8')
    manifest.append(dict(name=name,root=root.as_posix(),errors=list(errors),valid=valid))
case('valid',lambda d:None,valid=True)
case('cutout_canonical',lambda d:d.update({'bosses/golem.json':canonical_golem}),valid=True)
case('recipe_typo',lambda d:d['equipment.json'][0]['recipe'].update(golem_shrad=d['equipment.json'][0]['recipe'].pop('golem_shard')),['equipment.json:$[0].recipe.golem_shrad:존재하지 않는 materials id: golem_shrad'])
case('weapon_reference',lambda d:d['equipment.json'][0].update(weapon_id='missing'),['equipment.json:$[0].weapon_id:'])
case('drop_reference',lambda d:d['bosses/golem.json']['drops'][0].update(id='missing'),['bosses/golem.json:$.drops[0].id:'])
case('unlock_reference',lambda d:d['bosses/golem.json'].update(unlocks=['missing']),['bosses/golem.json:$.unlocks[0]:'])
case('phase_pattern_reference',lambda d:d['bosses/golem.json']['phases'][0]['patterns'][0].update(id='missing'),['bosses/golem.json:$.phases[0].patterns[0].id:'])
case('entry_pattern_reference',lambda d:d['bosses/wing.json']['phases'][2].update(enter_pattern='missing'),['bosses/wing.json:$.phases[2].enter_pattern:'])
case('missing_field',lambda d:d['tuning/player.json'].pop('move_speed'),['tuning/player.json:$.move_speed:필수 필드 누락'])
case('wrong_type',lambda d:d['tuning/player.json'].update(move_speed='fast',parry_enabled=1),['tuning/player.json:$.move_speed:','tuning/player.json:$.parry_enabled:'])
case('negative_value',lambda d:d['tuning/player.json'].update(dash_duration=-1),['tuning/player.json:$.dash_duration:'])
case('fractional_integer',lambda d:d['tuning/player.json'].update(potion_count=2.5),['tuning/player.json:$.potion_count:'])
case('unknown_field',lambda d:d['tuning/feedback.json'].update(shake_on_hitt=6),['tuning/feedback.json:$.shake_on_hitt:'])
case('unknown_effect',lambda d:d['equipment.json'][3]['effects'][0].update(type='magic'),['equipment.json:$[3].effects[0].type:'])
case('unknown_step',lambda d:d['bosses/golem.json']['patterns']['slam']['steps'][0].update(type='magic'),['bosses/golem.json:$.patterns.slam.steps[0].type:'])
case('nested_repeat_invalid',lambda d:d['bosses/golem.json']['patterns']['double_slam']['steps'][0]['steps'][0].update(type='bad_nested'),['bosses/golem.json:$.patterns.double_slam.steps[0].steps[0].type:'])
case('between_repeat_invalid',lambda d:d['bosses/golem.json']['patterns']['double_slam']['steps'][0]['between_steps'][0].update(duration='fast'),['bosses/golem.json:$.patterns.double_slam.steps[0].between_steps[0].duration:'])
case('duplicate_id',lambda d:d['materials.json'].append(copy.deepcopy(d['materials.json'][0])),['materials.json:$[4].id:중복 id:'])
case('phase_order',lambda d:d['bosses/wing.json']['phases'][1].update(hp_above=0.8),['bosses/wing.json:$.phases[1].hp_above:'])
case('phase_zero_missing',lambda d:d['bosses/wing.json']['phases'][2].update(hp_above=0.1),['bosses/wing.json:$.phases:마지막'])
case('drop_range',lambda d:d['bosses/golem.json']['drops'][0].update(min=9,max=2),['bosses/golem.json:$.drops[0]:min <= max'])
case('drop_partial',lambda d:d['bosses/golem.json']['drops'][0].pop('max'),['bosses/golem.json:$.drops[0]:min/max'])
case('projectile_index',lambda d:d['bosses/wing.json']['patterns']['fan_shot']['steps'][3].update(parriable_indices=[99]),['bosses/wing.json:$.patterns.fan_shot.steps[3].parriable_indices[0]:'])
case('missing_file',lambda d:d.pop('materials.json'),['materials.json:$:필수 파일 누락'])
case('malformed_json',lambda d:d.update({'materials.json':'[{"id":'}),['materials.json:$:JSON 구문 오류'])
case('null_root',lambda d:d.update({'materials.json':'null'}),['materials.json:$:JSON 구문 오류 또는 null 루트'])
case('root_type',lambda d:d.update({'equipment.json':{}}),['equipment.json:$:array 필요'])
case('unsupported_file',lambda d:d.update({'unknown.json':{}}),['unknown.json:$:지원하지 않는 데이터 파일'])
case('multiple_files',lambda d:(d['tuning/player.json'].pop('gravity'),d['tuning/feedback.json'].update(shake_on_hit=False),d['equipment.json'][0]['recipe'].update(typo=1)),['tuning/player.json:$.gravity:','tuning/feedback.json:$.shake_on_hit:','equipment.json:$[0].recipe.typo:'])
case('no_weapon_id',lambda d:d['equipment.json'][0].pop('weapon_id'),['equipment.json:$[0].weapon_id:'])
case('unknown_stat',lambda d:d['equipment.json'][0]['modifiers'].update(luck={'add':2}),['equipment.json:$[0].modifiers.luck:'])
case('bad_flag',lambda d:d['weapons.json'][0].update(flags=['magic']),['weapons.json:$[0].flags[0]:'])
case('negative_recipe',lambda d:d['equipment.json'][0]['recipe'].update(golem_shard=-1),['equipment.json:$[0].recipe.golem_shard:'])
case('telegraph_ambiguous',lambda d:d['bosses/golem.json']['patterns']['slam']['steps'][2].update(target='self'),['bosses/golem.json:$.patterns.slam.steps[2]:'])
case('bad_distance',lambda d:d['bosses/golem.json']['patterns']['slam'].update(min_distance=2000),['bosses/golem.json:$.patterns.slam:'])
case('bad_color',lambda d:d['bosses/golem.json']['body'].update(color=[2,0,0,1]),['bosses/golem.json:$.body.color[0]:'])
case('empty_combo',lambda d:d['weapons.json'][0].update(combo=[]),['weapons.json:$[0].combo:'])
case('mixed_same_file',lambda d:(d['equipment.json'][0].update(name=5),d['equipment.json'][0]['recipe'].update(missing=1)),['equipment.json:$[0].name:','equipment.json:$[0].recipe.missing:'])
case('mixed_boss_file',lambda d:(d['bosses/wing.json']['body'].update(size='bad'),d['bosses/wing.json']['phases'][0].update(enter_pattern='missing')),['bosses/wing.json:$.body.size:','bosses/wing.json:$.phases[0].enter_pattern:'])
case('practice_weapon_ref',lambda d:d['training.json']['player'].update(weapon_id='missing'),['training.json:$.player.weapon_id:'])
case('defaults_weapon_ref',lambda d:d['tuning_defaults.json']['training']['player'].update(weapon_id='missing'),['tuning_defaults.json:$.training.player.weapon_id:'])
case('defaults_duplicate_weapon',lambda d:d['tuning_defaults.json']['weapons'][1].update(id='sword_basic'),['tuning_defaults.json:$.weapons[1].id:'])
case('battle_boss_ref',lambda d:d['battle.json'].update(boss_id='missing'),['battle.json:$.boss_id:'])
case('battle_negative_lifetime',lambda d:d['battle.json'].update(projectile_lifetime=-1),['battle.json:$.projectile_lifetime:'])
case('battle_missing',lambda d:d.pop('battle.json'),['battle.json:$:필수 파일 누락'])
case('negative_stop_distance',lambda d:d['bosses/golem.json']['patterns']['slam']['steps'][1].update(stop_distance=-1),['bosses/golem.json:$.patterns.slam.steps[1].stop_distance:'])
case('invalid_direction_chain',lambda d:d['tuning/player.json'].update(attack_direction_chain=1),['tuning/player.json:$.attack_direction_chain:'])
case('defense_buffer_negative',lambda d:d['tuning/player.json'].update(defense_buffer=-1),['tuning/player.json:$.defense_buffer:'])
case('defense_flag_wrong_type',lambda d:d['tuning/player.json'].update(defense_cancel_hurt=1),['tuning/player.json:$.defense_cancel_hurt:'])
case('boolean_equipment_modifier',lambda d:d['equipment.json'][0]['modifiers'].update(defense_cancel_hurt={'add':1}),['equipment.json:$[0].modifiers.defense_cancel_hurt:'])
case('boss_initial_type',lambda d:d['bosses/golem.json'].update(initially_unlocked=1),['bosses/golem.json:$.initially_unlocked:'])
case('boss_order_negative',lambda d:d['bosses/golem.json'].update(order=-1),['bosses/golem.json:$.order:'])
case('chain_at_negative',lambda d:d['weapons.json'][0]['combo'][0].update(chain_at=-1),['weapons.json:$[0].combo[0].chain_at:'])
case('move_max_duration_zero',lambda d:d['bosses/golem.json']['patterns']['slam']['steps'][0].update(max_duration=0) if d['bosses/golem.json']['patterns']['slam']['steps'][0]['type']=='move_to' else next(step for step in d['bosses/golem.json']['patterns']['slam']['steps'] if step['type']=='move_to').update(max_duration=0),['max_duration:'])
case('device_switch_above_one',lambda d:d['tuning/player.json'].update(device_switch_axis=1.1),['tuning/player.json:$.device_switch_axis:'])
case('negative_vulnerable_gap',lambda d:d['tuning/player.json'].update(min_vulnerable_gap=-1),['tuning/player.json:$.min_vulnerable_gap:'])
case('dash_grace_negative',lambda d:d['tuning/player.json'].update(dash_direction_grace=-1),['tuning/player.json:$.dash_direction_grace:'])
case('dash_continuation_type',lambda d:d['tuning/player.json'].update(dash_attack_continues_after_dash=1),['tuning/player.json:$.dash_attack_continues_after_dash:'])
case('result_delay_negative',lambda d:d['battle.json'].update(result_input_delay=-1),['battle.json:$.result_input_delay:'])
case('bow_negative_damage',lambda d:d['tuning/player.json'].update(bow_damage_max=-1),['tuning/player.json:$.bow_damage_max:'])
case('bow_zero_lifetime',lambda d:d['tuning/player.json'].update(bow_lifetime=0),['tuning/player.json:$.bow_lifetime:'])
case('bow_wrong_charge_type',lambda d:d['tuning/player.json'].update(bow_charge_time='fast'),['tuning/player.json:$.bow_charge_time:'])
case('cutout_bad_window',lambda d:d.update({'bosses/golem.json':dict(canonical_golem,cutout=dict(canonical_golem['cutout'],moves=dict(canonical_golem['cutout']['moves'],slam=dict(canonical_golem['cutout']['moves']['slam'],active_end=.5))))}),['$.moves.slam:'])
case('cutout_unknown_clip',lambda d:d.update({'bosses/golem.json':dict(canonical_golem,cutout=dict(canonical_golem['cutout'],moves=dict(canonical_golem['cutout']['moves'],slam=dict(canonical_golem['cutout']['moves']['slam'],animation='walk'))))}),['.animation:'])
case('cutout_negative_scale',lambda d:d.update({'bosses/golem.json':dict(canonical_golem,cutout=dict(canonical_golem['cutout'],scale=-1))}),['.scale:'])
destination.mkdir(parents=True,exist_ok=True)
(destination/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
print(f'{len(manifest)} fixtures: {destination / "manifest.json"}')
